import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  apiSidebar: [
    {
      type: 'doc',
      id: 'index', // Points to 'api-docs/index.md'
      label: 'Table of Contents',
    },
    {
      type: 'category',
      label: 'Classes', // Display the 'classes' folder with uppercase label
      items: [
        {
          type: 'autogenerated',
          dirName: 'classes', // Points to the 'classes' folder
        },
      ],
    },
    {
      type: 'category',
      label: 'Interfaces', // Display the 'interfaces' folder with uppercase label
      items: [
        {
          type: 'autogenerated',
          dirName: 'interfaces', // Points to the 'interfaces' folder
        },
      ],
    },
  ],
};

export default sidebars;
